### ISSUE TITLE
代码块部分的小建议

### ISSUE THREAD

**Issue by 40huo** [Tokinx/Adams#1]
1. 行内代码高亮的部分好像有点问题，有些代码字体会变成 courier new，和正常的不一样；
1. 比较长的代码块会出现竖滚动条，对于查看代码不方便，建议只保留水平滚动条。

![](https://ooo.0o0.ooo/2017/06/27/595248ce300b5.png)

![](https://ooo.0o0.ooo/2017/06/27/595248f752baf.png)

**Comment by Tokinx** [comment]
1、我的php比较渣，欢迎提供比较好的正则方法，代码在function的154行，行内替换我的正则有问题。
2、考虑到较长的代码会占用较大的文章面积，我对代码块做了高度限制，且为了美观强制换行了（不会有水平滚动条）。
如果对这个方式不喜欢，建议在 后台->主题->自定义->额外CSS，对我的CSS进行覆盖处理：
![image](https://user-images.githubusercontent.com/4526339/27595884-7bfea0d8-5b90-11e7-98b7-f77ee725c532.png)

**Comment by 40huo** [comment]
```css
pre code{
max-height: 100%;
white-space: pre;
}
```
通过这样改成了竖直无滚动，水平有滚动，应该对的吧。。。
还发现了一个小问题
![](https://ooo.0o0.ooo/2017/06/28/5953a204bf4a8.png)
这里好像把字盖住了一点点？
