### ISSUE TITLE
能否提供下改成https的模式呢

### ISSUE THREAD

**Issue by xianlin6189** [Tokinx/Adams#10]
nginx做代理，apache做服务，但nginx访问的时候，相应的js全是访问的http模式，导致页面显示错误

**Comment by Tokinx** [comment]
<img src="https://ws4.sinaimg.cn/large/006tKfTcgy1fs6z0mg0mhj30lb0643z5.jpg"/>
检查这里（设置-常规）是否都是https，https并非主题所能控制，wp设置的问题即可
