### ISSUE TITLE
CDN 必须用千牛吗？

### ISSUE THREAD

**Issue by SaberOnGo** [Tokinx/Adams#100]
看了里边的代码，php代码里用到千牛CDN，是必须得用千牛吗？用其他可以吗

**Comment by Tokinx** [comment]
不是必须用七牛，知识最初是为七牛设计的这个东西，你只需要镜像自己的网站，在后台填入镜像的地址就可以了。
CDN地址和源站地址都能通过相同的url路径访问一个文件即可
例如：cdn.domain.com/aaa/bbb.jpg 和 www.domain.com/aaa/bbb.jpg
