### ISSUE TITLE
当设置页面为首页时，首页不显示文章标题  以及 评论出现艾特@两次的奇怪显示

### ISSUE THREAD

**Issue by CangShui** [Tokinx/Adams#102]
第一个问题：
我在header.php的29行插入
` <?php if (strcmp($_SERVER['REQUEST_URI'],"/" )==0) {  echo("<h1 class='fullname' id='homepage' >你的标题</h1>"); }else{ echo(""); }   ?> `
可以临时解决一下

第二个问题
<img src="https://dd-static.jd.com/ddimg/jfs/t1/173498/29/24219/11817/61c83ec8Ea6091fa2/c85d6868e02ac2aa.png" />

需修改functions.php第193行为：
`$comment_text = '<a href="#comment-' . $comment->comment_parent . '"></a> ' . $comment_text;`

**Comment by Tokinx** [comment]
没有理解你问题的意思
