### ISSUE TITLE
请问右上角社交菜单如何显示

### ISSUE THREAD

**Issue by wuzheng40** [Tokinx/Adams#104]
你好，非常喜欢这套主题，用了一下，右上角的社交菜单如何显示 能麻烦告知一下吗。
![微信图片_20220107101032](https://user-images.githubusercontent.com/1391798/148480178-eb34e23c-a413-4b11-9e52-c0f0783a15d4.png)
![微信图片_20220107101050](https://user-images.githubusercontent.com/1391798/148480183-5dbe4e19-ac4c-429d-8c3f-73f400f4431c.png)
![微信图片_20220107101135](https://user-images.githubusercontent.com/1391798/148480185-f139be62-b982-430c-b9b0-a632efe2bcdc.png)

**Comment by Tokinx** [comment]
![image](https://user-images.githubusercontent.com/4526339/148724929-23ae84f7-7860-4a58-bdd4-8935c3c744d1.png)

按照上方提示
1、创建一个菜单
2、添加菜单，CSS类是图标名称，可前往：草莓图标库 (chuangzaoshi.com) 获取图标name。
3、管理位置-社交连接，选择刚刚创建的菜单

主题已购买并取得了 “草莓 ICON” Pro 的授权许可，推荐使用。
