### ISSUE TITLE
error

### ISSUE THREAD

**Issue by eSouT** [Tokinx/Adams#13]
Warning: Declaration of description_walker::start_el(&$output, $item, $depth, $args) should be compatible with Walker_Nav_Menu::start_el(&$output, $item, $depth = 0, $args = Array, $id = 0) in /www/wwwroot/www.monoto.ml/wordpress/wp-content/themes/adams/inc/core.de.php on line 43
上传安装启用

**Comment by Tokinx** [comment]
尝试下载安装Github上的版本

**Comment by eSouT** [comment]
下载github的可以了(￣▽￣)"QAQ
