### ISSUE TITLE
列出目录的插件不兼容

### ISSUE THREAD

**Issue by Skywt2003** [Tokinx/Adams#15]
尝试很多生成文章目录的插件，以 Table of Contents Pllus 为例，出现如下情况：

- 点击文章目录链接会**在新窗口打开**（正常情况下应该平滑移动到指定标题位置）；
- 文章目录设定的样式会很奇怪，并且 hide/show 按钮消失……

尝试了几个类似功能的插件都有类似情况，使用默认主题或其他主题时一切正常……所以我认为是这个主题的兼容性问题。
关闭其他所有插件，问题仍然存在。
出现问题的页面示例：[https://skywt.cn/posts/slope/](https://skywt.cn/posts/slope/) 文章目录（content）部分。

**Comment by Tokinx** [comment]
主题使用了一款PJAX的JS插件，可能会与你安装的插件存在冲突。
你可以尝试在：后台-主题-自定义-主题设置，勾选“关闭PJAX”然后“发布”
操作完成之后再次开启你的插件。
如果问题依旧存在，可以在此issues下继续提交你所遇到的问题。

**Comment by Skywt2003** [comment]
感谢回复，尝试关闭 PJAX 后这个问题仍然存在……

**Comment by Tokinx** [comment]
针对这个问题我刚刚提交了更新
你可以从github中下载最新的版本以尝试解决
希望能够帮助到你

**Comment by Skywt2003** [comment]
更新后解决了，非常感谢！！
