### ISSUE TITLE
待优化文章长标题下一篇文章右箭头消失...

### ISSUE THREAD

**Issue by lalabg** [Tokinx/Adams#16]
1.单篇POST正文下面 上一篇下一篇文章处  如果2个主题标题均过长，下一篇标题后面的右箭头消失。
2.主题自定义中，追加自定义JS调用（例如百度站长的主动推送调用），会影响灯箱不正常或失效。
3.任意第三方相册插件，插入短代码无效（文章或页面）。
建议：如果有时间可以考虑加入无图片文章随机特色图像（例如上传某一文件夹/rpic，若干图片，随机调用作为特色头像显示在列表页）。

**Comment by Tokinx** [comment]
1、已更新到github
2、统计代码JS不需要script标签包裹。
3、插件冲突请尝试关闭Pjax，pjax冲突问题请自行解决，因为工作量问题我这边不会去适配。
很抱歉，随机图片这个可能建议不会采纳。建议使用子主题模式自行定制开发。
