### ISSUE TITLE
Chrome 上页面顶部空白较大

### ISSUE THREAD

**Issue by njuplus** [Tokinx/Adams#2]
主题在 Chrome 63 上页面顶部空白较大，控制台出现 `Failed to load resource: the server responded with a status of 500 (Internal Server Error)` 错误。在 Firefox 上没有问题。PS: 是在本地树莓派运行 (Raspbian LNMP)。

**Chrome (Console):**
![screen shot 2018-02-12 at 20 06 48](https://user-images.githubusercontent.com/20853639/36096302-be941f22-1030-11e8-86a3-fdba4cb4d525.png)

-------------------------------

**Chrome (Network):**
![screen shot 2018-02-12 at 20 12 27](https://user-images.githubusercontent.com/20853639/36096398-30c0e878-1031-11e8-80b3-4226360d6b9d.png)

-------------------------------
**Firefox:**
![screen shot 2018-02-12 at 20 14 12 1](https://user-images.githubusercontent.com/20853639/36096689-5837b840-1032-11e8-9888-9481952b1ed7.png)

**Comment by Tokinx** [comment]
设置SNS导航即可
