### ISSUE TITLE
评论异常

### ISSUE THREAD

**Issue by jovensun** [Tokinx/Adams#22]
wp版本: 5.2.2
Adams版本：1.3.7，最新Release版
xampp版本：3.2.4
异常现象：
![image](https://user-images.githubusercontent.com/19667184/61581010-1c777b00-ab4b-11e9-92bb-0ececf93b8dc.png)

**Comment by Tokinx** [comment]
为什么关闭了issues？问题解决了嘛？我这边没有复现该错误，请提供PHP版本信息
