### ISSUE TITLE
dangopress_esc_callback

### ISSUE THREAD

**Issue by Thiece** [Tokinx/Adams#26]
Warning: Use of undefined constant dangopress_esc_callback - assumed 'dangopress_esc_callback' (this will throw an Error in a future version of PHP) in 
/wp-content/themes/Adams-1.3.7/functions.php on line 162

**Comment by Tokinx** [comment]
什么环境？
PHP版本多少，Apache还是Nginx。
先下载github上最新的版本（不是releases里的稳定版）
