### ISSUE TITLE
建议不要引用loli.net的资源库

### ISSUE THREAD

**Issue by luminouskk** [Tokinx/Adams#35]
loli.net的备案已经掉了很久了，服务器也从之前的香港阿里云换到了更便宜的线路

基本上谈不上加速了，而且在特定环境下是大幅的减速，他家的香港IPv6境内三网均绕美/绕欧

比如他家谷歌字体，连IPv4都切德国去了
[![8Qj0Re.png](https://s1.ax1x.com/2020/03/14/8Qj0Re.png)](https://imgchr.com/i/8Qj0Re)
[![8QjrMd.png](https://s1.ax1x.com/2020/03/14/8QjrMd.png)](https://imgchr.com/i/8QjrMd)

字体建议考虑360的静态资源库
https://cdn.baomitu.com/index/fonts

**Comment by Tokinx** [comment]
这CDN前后换了几次了，我看回头我把字体丢到主题里算了，也别引用第三方了。

**Comment by Tokinx** [comment]
直接删掉了Exo2字体，省心了。
这个字体当时在google fonts上挑了好久，不过不用也不影响什么。
需要的话可以自己在主题自定义内自己加上。
