### ISSUE TITLE
小请求:可不可以在导航菜单里做一个下拉式的菜单

### ISSUE THREAD

**Issue by NiTian1207** [Tokinx/Adams#36]
我因为文章分类比较多,导航栏塞得有点满

**Comment by Tokinx** [comment]
你好，因为主题出于精简考虑，所以导航部分使用的是overflow-y: hidden;方式来处理移动端显示问题，所以下拉菜单普通方式难以实现，权衡后暂不考虑增加下拉菜单功能，非常抱歉。
你也可以通过子主题的方式对主题进行二次开发以满足需求

**Comment by NiTian1207** [comment]
> 你好，因为主题出于精简考虑，所以导航部分使用的是overflow-y: hidden;方式来处理移动端显示问题，所以下拉菜单普通方式难以实现，权衡后暂不考虑增加下拉菜单功能，非常抱歉。
> 你也可以通过子主题的方式对主题进行二次开发以满足需求

好的,感谢回复.
我还有一个小问题,进后台的时候,排版会出错,刷新一下就正常了,是什么设置错误了吗

**Comment by Tokinx** [comment]
因为PJAX只加载html，不会重复加载CSS、JS等文件，所以通过普通点击的方式（pjax）进入后台会出现后台样式错误的问题。
解决方法为：关闭PJAX，或者右键-新窗口打开链接（win：ctrl+鼠标左键；mac：cmd+鼠标左键）
