### ISSUE TITLE
收款方式设置后，不显示已设置的图片

### ISSUE THREAD

**Issue by w4o** [Tokinx/Adams#37]
![image](https://user-images.githubusercontent.com/13061300/76822160-2b820a80-684b-11ea-9efd-0cc97cbd2902.png)

**Comment by Tokinx** [comment]
这个地方建议看看是不是你配置的有问题，主题默认设置过收款方式之后，这里是能看到图片的。
建议仔细排查一下。
你修改的push我看了下，建议尝试部署一个全新的wp环境，测试可有bug

**Comment by w4o** [comment]
刚刚测试过了，在一个全新的Wordpress环境中不确实存在这个问题；我已经将PR关掉了。
