### ISSUE TITLE
进后台的时候PJAX导致排版会出错

### ISSUE THREAD

**Issue by w4o** [Tokinx/Adams#41]
我看之前@NiTian1207 在的#36 [issues里](https://github.com/Tokinx/Adams/issues/36#issuecomment-599501133) 也提到过该问题；当时并没有解决。

**Comment by Tokinx** [comment]
有提过，进后台新标签页打开就行了。设置一下。
你如果觉得不方便，可以用其它方式判断是否是后台，令其自动新窗口打开即可。
