### ISSUE TITLE
当社交链接为图片时，与页面其他元素冲突

### ISSUE THREAD

**Issue by w4o** [Tokinx/Adams#44]
![image](https://user-images.githubusercontent.com/13061300/77137509-3d60e900-6aa9-11ea-94f2-d95eafba5cb0.png)

**Comment by Tokinx** [comment]
Thanks，已合并
非常感谢。当时测的时候因为我这边有设置导航，所以没测到遮挡问题。

**Comment by w4o** [comment]
😳😳😳
被文章页“赏”字遮挡。
![image](https://user-images.githubusercontent.com/13061300/77153614-09032200-6ad5-11ea-8aae-6bdb84205924.png)
