### ISSUE TITLE
社交链接图片无法显示

### ISSUE THREAD

**Issue by L245T** [Tokinx/Adams#49]
不知道是不是我设置错了，我是直接在自定义中添加菜单，设置为社交
[![设置以及实际显示](https://blogimglzxz.oss-cn-shanghai.aliyuncs.com/issue/social_issue.png "设置以及实际显示")](https://blogimglzxz.oss-cn-shanghai.aliyuncs.com/issue/social_issue.png "设置以及实际显示")
社交图片在1.3.11、1.4.19、1.4.2版本中都无法正确显示，如上图
wordpress版本 5.3.2–zh_CN
PHP版本 72

**Comment by Tokinx** [comment]
仔细阅读https://biji.io/2017/4905.html
需要访问caomei icon的地址获取图标名称，然后正确配置。
