### ISSUE TITLE
关于主题文件命名的小建议

### ISSUE THREAD

**Issue by w4o** [Tokinx/Adams#51]
今天在Wordpress debug.log 中发现了大量 `Notice`。

![image](https://user-images.githubusercontent.com/13061300/78094408-14c0e380-7407-11ea-83dd-38360a65a5be.png)

根据[wordpress 官方开发文档](https://codex.wordpress.org/zh-cn:%E4%B8%BB%E9%A2%98%E5%BC%80%E5%8F%91#.E6.A8.A1.E6.9D.BF.E6.96.87.E4.BB.B6.E5.88.97.E8.A1.A8)，是因为我们主题中，评论模版文件叫 `comment.php`，而不是文档中要求的`comments.php`导致的。

建议大佬有时间修改一下。😄

**Comment by Tokinx** [comment]
已修改
