### ISSUE TITLE
关于标题的一个小建议

### ISSUE THREAD

**Issue by Manshaoco** [Tokinx/Adams#52]
在移动端这边较长的标题换行后，行间距比较小，看起来会有些不自然，希望能适当将标题的行间距调大一点。感谢作者和相关贡献者，这部作品真的是WP免费主题里的一股清流

**Comment by Tokinx** [comment]
已更新，暂未推送。github clone下载更新到wp看看吧？

**Comment by Manshaoco** [comment]
> 已更新，暂未推送。github clone下载更新到wp看看吧？

好的，多谢！
