### ISSUE TITLE
图片不能正常显示的问题

### ISSUE THREAD

**Issue by StefanZhang** [Tokinx/Adams#53]
博客里面的图片都不能正常显示了,文章的预览还是可以看到的,但是发布以后图片就看不到了, 只能看到为图片预留出来的空白,如果双击这个空白也是可以看到图片的放大版本,请问这是什么问题呢?

看到了之前的issue, 问题应该是一样,关闭PJAX 也不能解决, 图片路径也没有中文的

**Comment by StefanZhang** [comment]
再给一个链接 https://stefanzhang.com/?p=184

**Comment by Tokinx** [comment]
看看你的插件，关闭懒加载。

**Comment by StefanZhang** [comment]
感谢，已经解决。
