### ISSUE TITLE
评论重复提交

### ISSUE THREAD

**Issue by chnyuwen** [Tokinx/Adams#54]
环境：CDN，插件全部关闭。
复现：
1. 清除浏览器缓存，首次提交评论，评论重复提交，继续提交评论，仍重复提交。
2. 刷新后再提交评论不再重复提交。

**Comment by Tokinx** [comment]
是的，这个问题已经发现了，但是最近比较忙，我抽时间看一下，试试关闭PJAX能否解决。

**Comment by Tokinx** [comment]
这个问题现在已经修复了，但是暂时没又推送更新，你可以在github clone一个下来更新到wp上
