### ISSUE TITLE
按回退键后页面没有回退

### ISSUE THREAD

**Issue by Humengchao** [Tokinx/Adams#58]
大佬，我用您的主题后发现有个问题，就是当按下回退键后地址栏中的url变成了上一个页面的url，但是页面并没有返回，还是当前页面，要主动去点击下刷新才行。 而且pc段和移动端我都试过，都是这个问题。  请问有什么解决方案吗？   https://wqnmd.net

**Comment by Tokinx** [comment]
电脑端：Chrome、Edge、Safari，移动端：Safari。均未复现该问题。
已知该问题仅在评论翻页时会出现，但暂不考虑修复。其它页面均正常前进后退。

**Comment by Humengchao** [comment]
嗯，那时候好像是我的wordpress出问题了，我那时候重装了好几次主题不行，换了台机器发现没毛病后，重装了下原来有问题的那个wordpress，就好了



---原始邮件---
发件人: "Cheng"<notifications@github.com&gt;
发送时间: 2020年5月1日(周五) 中午1:26
收件人: "Tokinx/Adams"<Adams@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Humengchao"<810244965@qq.com&gt;;
主题: Re: [Tokinx/Adams] 按回退键后页面没有回退 (#58)




 
电脑端：Chrome、Edge、Safari，移动端：Safari。均未复现该问题。
 已知该问题仅在评论翻页时会出现，但暂不考虑修复。其它页面均正常前进后退。
