### ISSUE TITLE
呼叫总部：密码问题重大BUG

### ISSUE THREAD

**Issue by a1797831629** [Tokinx/Adams#59]
随意选一篇文章输了密码之后，所有密码相同的文章全开了，

**Comment by Tokinx** [comment]
默认主题测试了吗？Adams并没有处理密码这块儿的相关代码，仅仅是新增了密码文章CSS。和原生的一些判断方式。如果原生主题没问题，那可能是我判断的地方用法有问题。你先试试。

**Comment by Tokinx** [comment]
不小心关闭了。。。
