### ISSUE TITLE
图片点开灯箱效果会被顶栏覆盖

### ISSUE THREAD

**Issue by cantime** [Tokinx/Adams#6]
![feedback](https://user-images.githubusercontent.com/36782547/39965142-4b8db074-56c6-11e8-8cee-3d56a18ea792.jpg)

**Comment by Tokinx** [comment]
好的，抽时间我会修复一下，最近比较忙

**Comment by cantime** [comment]
谢谢大神，很喜欢你这款主题，看得出用心了。
希望大神指教一下怎么修改默认字体为另外一款，目前的是粗体不太喜欢。

**Comment by Tokinx** [comment]
灯箱问题已修复，Github下载最新的style.css即可：https://github.com/Tokinx/Adams/blob/master/style.css

修改字体可以前往后台-主题-编辑CSS-额外的CSS下，添加下面代码保存即可：
```
body {
    font-family:serif;
}
```
