### ISSUE TITLE
有一处1像素的错位，本人CSS不好，没能修复成功，大神处理一下

### ISSUE THREAD

**Issue by keinx** [Tokinx/Adams#63]
文章右侧的扫码手机访问和打赏，不在一个水平线，强迫症看着有点难受。  
如下图：  
![bug](https://user-images.githubusercontent.com/3890705/82826602-0a3f3980-9ee0-11ea-95c5-242c276738aa.png)

**Comment by cl773915148** [comment]
进入 wp-content/themes/Adams-1.4.26 目录下找到 style.css line:128
将
`.infos .share{float: left;}`
改为
`.infos .share{line-height:50px;float: left;}`

**Comment by keinx** [comment]
> 进入 wp-content/themes/Adams-1.4.26 目录下找到 style.css line:128
> 将
> `.infos .share{float: left;}`
> 改为
> `.infos .share{line-height:50px;float: left;}`

非常感谢

**Comment by Tokinx** [comment]
非常不建议修改主题源码，建议进入后台-主题-自定义-额外的CSS，填入`.infos .share{line-height:50px;}`发布即可

**Comment by Tokinx** [comment]
这个问题下个版本会尝试修复
