### ISSUE TITLE
小图标加载失败的问题

### ISSUE THREAD

**Issue by StefanZhang** [Tokinx/Adams#64]
尝试很多不同的办法，但是右侧的小图标都加载失败，用的是海外vultr的主机，这个库有办法替换成别的吗？
如下图
<img width="482" alt="截屏2020-05-25 下午2 16 38" src="https://user-images.githubusercontent.com/10293941/82835624-962a7480-9e92-11ea-81dc-551ac987344b.png">

**Comment by Tokinx** [comment]
文件丢OSS、七牛或者别的CDN吧。图标字体没加载出来
