### ISSUE TITLE
从博客首页跳转到登录界面或者是博客后台时排版崩溃

### ISSUE THREAD

**Issue by ChrisKimZHT** [Tokinx/Adams#65]
难道我是个例嘛？我用其他的主题没出现这个现象。
另外排版崩溃时的界面右侧滚动条还是首页的样式，是首页和后台样式不兼容还是啥，我也不太懂。

![QQ截图20200603142525](https://user-images.githubusercontent.com/49368462/83605402-6eca5a80-a5aa-11ea-9922-913b90717067.png)
![QQ截图20200603142619](https://user-images.githubusercontent.com/49368462/83605407-6ffb8780-a5aa-11ea-92be-0cb7019f511b.png)

**Comment by ChrisKimZHT** [comment]
出现这种情况后，手动刷新就能恢复。
但是如果切换回首页刷新一下再进后台，又出现这个问题。

**Comment by Tokinx** [comment]
ajax不会自动加载后台样式，建议讲后台链接设置为新窗口打开

**Comment by ChrisKimZHT** [comment]
啊，好吧。那请问下大佬怎么设置成新窗口打开，每次右键点打开新窗口不太方便。

**Comment by Tokinx** [comment]
你找到设置方法了吧，编辑菜单的时候可以勾选新窗口打开
