### ISSUE TITLE
护眼模式/夜晚模式 评论区竖线对不齐

### ISSUE THREAD

**Issue by ChrisKimZHT** [Tokinx/Adams#66]
如图，只有默认模式正常。
![image](https://user-images.githubusercontent.com/49368462/83612809-81965c80-a5b5-11ea-94c0-6a80932e66ed.png)
![image](https://user-images.githubusercontent.com/49368462/83612827-865b1080-a5b5-11ea-9b46-4ff1229bbf30.png)
![image](https://user-images.githubusercontent.com/49368462/83612842-8bb85b00-a5b5-11ea-93af-5a7b77dc1138.png)

（没错，又是我。不够作者做的这个主题真的是非常非常完美！我从其他主题换过来，就只有这个出的bug最少，插件全部不出毛病）

**Comment by Tokinx** [comment]
这个问题较早时候就发现了，我计划抽时间用Sass、Less重写CSS部分顺便解决这个问题。
其它未来的更新计划在我的博客也有列一些。
感谢你的支持。
