### ISSUE TITLE
代码高亮相关的问题

### ISSUE THREAD

**Issue by JimmyTinsley** [Tokinx/Adams#67]
作者大大你好, 首先感谢你开发这款主题, 相当漂亮, 很赞!

然后我有两个代码高亮相关的问题哈. 

第一个是我发现用markdown编写文章发布时, 如果一个段落里面有多段行内代码, 好像只有第一段会成功渲染出彩色, 后面的都是灰色的. 比如说有如下的一段内容:

This is `code section 1 style 1`, this is `code section 2 style 1`, and this is `code section 3 style 1`.
This is `code section 4 style 2`, this is `code section 5 style 2`, and this is `code section 6 style 2`.

在文章发布后的渲染效果是这样的:
![图片](https://user-images.githubusercontent.com/37508117/84363781-c8adce80-ac01-11ea-84d3-a01659c5a99d.png)

在网页上审查元素时发现:
![图片](https://user-images.githubusercontent.com/37508117/84363936-01e63e80-ac02-11ea-88d3-9b1b81b8cd6d.png)
只有第一段行内代码是渲染出了`class="prettyprint prettyprinted"`的.

我排查了插件中可能导致冲突的WP Githuber MD插件, 禁用之后还是相同的结果. 不知道这是个bug还是我自己的配置有问题?

第二个问题是, 如果我不喜欢默认的代码高亮风格, 请问应该如何替换呢? 我对php不太熟, 找了挺久的代码也没找到在什么地方. 或者说, 有没有可能把切换代码高亮风格做成一个配置, 在主题自定义中选择呢?

**Comment by Tokinx** [comment]
好像是我正则写的有点问题。这个我回头看下。
如果不喜欢默认的代码高亮，可以在主题自定义里关闭默认的代码高亮（我记得好像加开关了）然后再自行按照自己的喜好添加自己喜欢的代码高亮插件。如果插件有问题，可能需要关闭pjax

**Comment by JimmyTinsley** [comment]
感谢回复, 安装了代码高亮插件, 替换成功了
