### ISSUE TITLE
网站公告一言失效

### ISSUE THREAD

**Issue by ChrisKimZHT** [Tokinx/Adams#68]
网站空公告的随机句子没了，估计是API失效了。找了半天源码在哪也没找着……（我太菜了）

**Comment by Tokinx** [comment]
非常感谢，这个问题现在已经修复了，稍后会推送更新。
另外修复了标签过多无法自动换行的问题。
你也可以直接在Github上Clone Master分支的代码

**Comment by ChrisKimZHT** [comment]
好奇怪，为啥Clone了最新的代码安装，还是不显示呢

**Comment by Tokinx** [comment]
代码提交错了。现在好了
