### ISSUE TITLE
希望增加“xx条评论”可以点击直接评论

### ISSUE THREAD

**Issue by wddd27** [Tokinx/Adams#72]
目前使用的版本是1.4.26
如题，希望后续能增加xx条评论可以点击直接转跳评论或者转跳文章的功能，原因可能是朋友圈用户习惯导致，朋友对着屏幕上的“xx条评论”狂点，并问怎么点不进去....（哈哈哈，大佬的主题能自动切换夜间模式很赞～吹爆～

**Comment by Tokinx** [comment]
我记得当时这个地方是我刻意删掉link点击效果的。目的是为了跟两边的“时间”、“喜欢”功能保持一致（仅做展示而不是跳转链接用）
建议使用子主题方式自行修改。
