### ISSUE TITLE
已经是1.4.29版本，但是后台还是提示要更新到1.4.29

### ISSUE THREAD

**Issue by huangzong1998** [Tokinx/Adams#73]
更新之后还是有提示，虽然没有什么影响，但还是反馈一下

**Comment by Tokinx** [comment]
检查一下是不是主题目录大小写或者主题目录名称跟更新的目录不一致导致的？

**Comment by ChrisKimZHT** [comment]
好像的确有这个问题，无限更新

**Comment by Tokinx** [comment]
好的，我看下这个问题。

**Comment by Tokinx** [comment]
找到问题了，是我代码里设置的adams，但是打包发布的文件夹是Adams导致的，正好更新了一些东西，新版本打包文件夹用回了小写的admas。
