### ISSUE TITLE
作者您好，我非常喜欢你的主题，想移植到hexo

### ISSUE THREAD

**Issue by FuShaoLei** [Tokinx/Adams#75]
作者您好 我是一名hexo爱好者，也是hexo主题white的作者，机缘巧合看到了你这个主题，觉得非常简洁 又有些个性，想移植到hexo，我将写明上原作地址和原作者，不知你意下如何 ？

**Comment by Tokinx** [comment]
非常感谢，欢迎你将Adams移植到其他平台，如果需要技术或其它方面的支持也可以随时联系我。
