### ISSUE TITLE
希望增加一个主题默认样式设置

### ISSUE THREAD

**Issue by FastChen** [Tokinx/Adams#76]
希望可以在主题里设置站点默认的主题颜色(默认，护眼，夜晚)和字体样式(Serif，Sans)

**Comment by Tokinx** [comment]
真的很感谢你的支持。

默认主题模式不需要更新主题，按照以下步骤即可：

后台-外观-自定义-主题设置-页脚追加JS代码，添加下面代码：

默认白天模式：$('.setting_tool .undefined').click();

默认护眼模式：$('.setting_tool .sepia').click();

默认夜晚模式：$('.setting_tool .night').click();

如图：https://i.loli.net/2019/06/21/5d0cc2bb46a5f57108.png
