### ISSUE TITLE
关于主页显示摘要字数疑问❓

### ISSUE THREAD

**Issue by ChiehJang** [Tokinx/Adams#79]
请问主页显示摘要字数数量可以修改吗。我百度了找到的修改$excerpt_length = apply_filters(‘excerpt_length’, 55);$excerpt_more = apply_filters(‘excerpt_more’, ‘ ‘ . ‘[...]‘);，但是似乎没有作用于本主题。望有空指点一下。

**Comment by Tokinx** [comment]
修改主题目录下index.php文件的第22行，220字改为你需要的字数即可。
建议使用子主题方式对主题进行二次开发，避免主题后续推送更新覆盖你的修改。
