### ISSUE TITLE
warning in php 8.0.0

### ISSUE THREAD

**Issue by woodwm** [Tokinx/Adams#80]
Warnings are shown in the front page when `php 8.0.0` is used.

```js
Warning: Attempt to read property "before" on array in /srv/disk6/2749657/www/woodslow.ml/wp-content/themes/Adams/inc/core.de.php on line 35

Warning: Attempt to read property "link_before" on array in /srv/disk6/2749657/www/woodslow.ml/wp-content/themes/Adams/inc/core.de.php on line 37

Warning: Attempt to read property "link_after" on array in /srv/disk6/2749657/www/woodslow.ml/wp-content/themes/Adams/inc/core.de.php on line 38

Warning: Attempt to read property "after" on array in /srv/disk6/2749657/www/woodslow.ml/wp-content/themes/Adams/inc/core.de.php on line 40
```

**Comment by waloyn** [comment]
me too.
Warning: Attempt to read property "before" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 35
Warning: Attempt to read property "link_before" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 37
Warning: Attempt to read property "link_after" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 38
Warning: Attempt to read property "after" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 40
Warning: Attempt to read property "before" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 35
Warning: Attempt to read property "link_before" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 37
Warning: Attempt to read property "link_after" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 38
Warning: Attempt to read property "after" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 40
Warning: Attempt to read property "before" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 35
Warning: Attempt to read property "link_before" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 37
Warning: Attempt to read property "link_after" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 38
Warning: Attempt to read property "after" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 40
Warning: Attempt to read property "before" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 35
Warning: Attempt to read property "link_before" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 37
Warning: Attempt to read property "link_after" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 38
Warning: Attempt to read property "after" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 40
Warning: Attempt to read property "before" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 35
Warning: Attempt to read property "link_before" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 37
Warning: Attempt to read property "link_after" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 38
Warning: Attempt to read property "after" on array in e:\document\wordpress\wp-content\themes\Adams-1.4.26\inc\core.de.php on line 40

**Comment by Tokinx** [comment]
你们的 PHP 版本更新的好勤快呀。。。
最近网络断掉了，等五一后网络恢复考虑适配 PHP8，实在抱歉

**Comment by Tokinx** [comment]
安装了php 8.0.11，并未出现任何报错信息。
