### ISSUE TITLE
读者墙没有显示啊

### ISSUE THREAD

**Issue by guduing** [Tokinx/Adams#89]
读者墙没有显示啊。
pjax会导致手机端文章内嵌的视频无法播放。关闭的情况下一言又挂了。
代码高亮也有问题，会显示好多重复代码。
使用环境Adams1.54，wordpress5.72,php7.2,mysqli 5.5.19
大佬快更新。

**Comment by Tokinx** [comment]
留下博客地址吧。
pjax关闭一言无效问题马上修复。手机端视频问题不太好改，我下班看下吧。
代码高亮如果同段落多处代码会只有第一个可以高亮，因为正则匹配有点问题，暂时没找到好的解决办法。
稍后你可以拉取github最新代码以修复关闭pjax一言失效问题。

**Comment by guduing** [comment]
读者墙可以了。代码高亮问题，你看下这个页面  https://jun.red/not/340.html
另外,发现pjax关掉的情况下，如果开启自动夜间模式会导致无法在前台更改模式，切换页面后设置会无效。

**Comment by Tokinx** [comment]
没有发现关闭pjax切换模式导致设置无效的问题
