### ISSUE TITLE
功能意见：搜索功能以及tag标签

### ISSUE THREAD

**Issue by zenonux** [Tokinx/Adams#92]
感觉搜索功能不是很方便，点击的位置以及交互有点繁琐，不利于快速查找自己写过的文章。tag标签其实也是为了快速查找自己的文章，首页也没有tag显示的地方。不知道有没有好的方式处理

**Comment by Tokinx** [comment]
怎么说呢，每个人对一些特定功能的优先级定义不一样，在做这款主题前，我认为读者更优先关注的是最新的文章，所以搜索放在了不重要的位置，标签功能最初也是不支持的，也是后期加进去的，首页没有预留标签的位置。
这都是主题设计之初的特性，相信你实用Adams也是因为大部分功能和设计满足的所需，但是主题实在无法满足所有人的需求，如果某些地方我没有采纳也请见谅，你可以实用子主题方式对Adams进行二次开发以实现所需要的的功能。
非常感谢你的支持与建议
